### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Profpatsch** [rotty/spells#2]
http://rotty.yi.org/software/spells/ leads nowhere.

**Comment by rotty** [comment]
Thanks, fixed.

**Comment by Profpatsch** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/3153638/8273866/4fbccb86-187f-11e5-90e9-5ff6825350a4.jpg)

**Comment by rotty** [comment]
Well, yes rotty.yi.org is no more, I've changed the link in the spells README.
